### Team
GET http://localhost:4000/teams HTTP/1.1

###

GET http://localhost:4000/teams/66eea633541a278643517590 HTTP/1.1

###

POST http://localhost:4000/teams HTTP/1.1
content-type: application/json

{
  "name": "DK",
  "logoURL": ""
}

###

PATCH http://localhost:4000/teams/66eea633541a278643517590 HTTP/1.1
content-type: application/json

{
  "pin": 1234
}
###

DELETE  http://localhost:4000/teams/66efe50cbede4f3666e08ff1 HTTP/1.1

###