name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Add host key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 7822 200.69.21.71 >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Pull latest code to server
        run: |
          ssh -p 7822 pnviethung@200.69.21.71 'cd ~/bot && git pull origin main'
      - name: Login to Docker Hub
        run: docker login -u pnviethung -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull pnviethung/jackbot:latest
      - name: Run Docker container
        run: docker run -d -p 3000:3000 pnviethung/jackbot:latest
