name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v4
      - name: echo
        run: echo "Connecting to server ${{ secrets.HOST }} - password: ${{ secrets.PASSWORD }}";
      - uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}

      - name: Login to Docker Hub
        run: docker login -u pnviethung -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker image
        run: docker pull pnviethung/jackbot:latest
      - name: Run Docker container
        run: docker run -d -p 3000:3000 pnviethung/jackbot:latest
